services:
  postgres:
    image: postgres:15
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    command:
      - start-dev
      - --http-port=8080
      - --metrics-enabled=true
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-net

  docker-stats-exporter:
    build:
      context: ./docker-stats-exporter
    container_name: docker-stats-exporter
    environment:
      CONTAINER_NAME: keycloak
      SCRAPE_INTERVAL: "5"
      LISTEN_PORT: "9323"
      DOCKER_HOST: tcp://host.docker.internal:2375
    ports:
      - "9323:9323"
    networks:
      - keycloak-net


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - docker-stats-exporter
    networks:
      - keycloak-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - keycloak-net

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    command:
      - '--config.file=/config/blackbox.yml'
    ports:
      - "9115:9115"
    networks:
      - keycloak-net
  locust:
    image: locustio/locust:2.42.1
    container_name: locust
    command:
      - -f
      - /mnt/locust/keycloak_loadtest.py
      - --web-host
      - 0.0.0.0
      - --web-port
      - "8089"
      - --host
      - http://keycloak:8080
    ports:
      - "8089:8089"
    volumes:
      - ./keycloak_loadtest.py:/mnt/locust/keycloak_loadtest.py:ro
    networks:
      - keycloak-net
    depends_on:
      - keycloak
  
  locust-exporter:
    build: ./locust-exporter
    container_name: locust-exporter
    environment:
      - LOCUST_URL=http://locust:8089
      - LISTEN_PORT=9324
      - SCRAPE_INTERVAL=5
    networks:
      - keycloak-net
    depends_on:
      - locust




volumes:
  postgres_data:

networks:
  keycloak-net:
