global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'keycloak-account-probe'
    metrics_path: /probe
    params:
      module: [http_keycloak_account] 
    static_configs:
      - targets:
          - http://keycloak:8080/realms/master/account/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
